//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStillDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RunHeader()
        {
            this.RunRecords = new HashSet<RunRecord>();
        }
    
        public int rhID { get; set; }
        public System.DateTime rhDate { get; set; }
        public System.DateTime rhStart { get; set; }
        public System.DateTime rhEnd { get; set; }
        public System.TimeSpan rhDuration { get; set; }
        public bool rhComplete { get; set; }
        public string rhUnits { get; set; }
        public Nullable<decimal> rhAvgPressure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunRecord> RunRecords { get; set; }
    }
}
